
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analisis.olc;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int truta = 4;
  public static final int coma = 10;
  public static final int cadena = 14;
  public static final int tproyecto = 2;
  public static final int llavei = 12;
  public static final int tconfiguracion = 3;
  public static final int tfecha = 8;
  public static final int EOF = 0;
  public static final int llaved = 13;
  public static final int tcorrer = 6;
  public static final int dospuntos = 11;
  public static final int error = 1;
  public static final int tnombre = 5;
  public static final int tcarpeta = 9;
  public static final int tarchivo = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tproyecto",
  "tconfiguracion",
  "truta",
  "tnombre",
  "tcorrer",
  "tarchivo",
  "tfecha",
  "tcarpeta",
  "coma",
  "dospuntos",
  "llavei",
  "llaved",
  "cadena"
  };
}

