
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analisis.Grafica;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int menos = 76;
  public static final int menor = 22;
  public static final int punto = 65;
  public static final int nulo = 27;
  public static final int booleano = 86;
  public static final int decremento = 64;
  public static final int leerarchivo = 46;
  public static final int print = 16;
  public static final int tchar = 4;
  public static final int suma = 75;
  public static final int importar = 37;
  public static final int tochar = 51;
  public static final int println = 17;
  public static final int tvoid = 26;
  public static final int aumento = 63;
  public static final int div = 78;
  public static final int romper = 59;
  public static final int cadena = 82;
  public static final int dospuntos = 62;
  public static final int menorigual = 23;
  public static final int mientras = 57;
  public static final int abstracto = 28;
  public static final int privado = 40;
  public static final int sino = 71;
  public static final int tint = 2;
  public static final int toint = 53;
  public static final int decimal = 85;
  public static final int caso = 29;
  public static final int try_ = 55;
  public static final int sinosi = 70;
  public static final int str_ = 54;
  public static final int llavei = 8;
  public static final int or = 68;
  public static final int caracter = 83;
  public static final int llaved = 9;
  public static final int extiende = 34;
  public static final int mayorigual = 24;
  public static final int nuevo = 39;
  public static final int tolower = 73;
  public static final int id = 12;
  public static final int retorno = 43;
  public static final int estatico = 47;
  public static final int desigual = 20;
  public static final int cat = 30;
  public static final int protegido = 41;
  public static final int puntocoma = 7;
  public static final int and = 67;
  public static final int mayor = 21;
  public static final int printable = 80;
  public static final int xor = 79;
  public static final int tbool = 5;
  public static final int EOF = 0;
  public static final int escribir = 56;
  public static final int super_ = 48;
  public static final int tstring = 6;
  public static final int este = 50;
  public static final int tostring = 72;
  public static final int publico = 42;
  public static final int arroba = 44;
  public static final int potencia = 25;
  public static final int corchetei = 13;
  public static final int touper = 74;
  public static final int multi = 77;
  public static final int interrogante = 61;
  public static final int error = 1;
  public static final int switch_ = 49;
  public static final int corcheted = 14;
  public static final int continuar = 60;
  public static final int si = 69;
  public static final int entero = 84;
  public static final int graph = 36;
  public static final int sobrescrito = 45;
  public static final int pari = 10;
  public static final int hacer = 33;
  public static final int defecto = 32;
  public static final int igualigual = 19;
  public static final int pard = 11;
  public static final int para = 58;
  public static final int tdouble = 3;
  public static final int coma = 18;
  public static final int instanceof_ = 38;
  public static final int modulo = 81;
  public static final int not = 66;
  public static final int final_ = 35;
  public static final int igual = 15;
  public static final int todouble = 52;
  public static final int clase = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tint",
  "tdouble",
  "tchar",
  "tbool",
  "tstring",
  "puntocoma",
  "llavei",
  "llaved",
  "pari",
  "pard",
  "id",
  "corchetei",
  "corcheted",
  "igual",
  "print",
  "println",
  "coma",
  "igualigual",
  "desigual",
  "mayor",
  "menor",
  "menorigual",
  "mayorigual",
  "potencia",
  "tvoid",
  "nulo",
  "abstracto",
  "caso",
  "cat",
  "clase",
  "defecto",
  "hacer",
  "extiende",
  "final_",
  "graph",
  "importar",
  "instanceof_",
  "nuevo",
  "privado",
  "protegido",
  "publico",
  "retorno",
  "arroba",
  "sobrescrito",
  "leerarchivo",
  "estatico",
  "super_",
  "switch_",
  "este",
  "tochar",
  "todouble",
  "toint",
  "str_",
  "try_",
  "escribir",
  "mientras",
  "para",
  "romper",
  "continuar",
  "interrogante",
  "dospuntos",
  "aumento",
  "decremento",
  "punto",
  "not",
  "and",
  "or",
  "si",
  "sinosi",
  "sino",
  "tostring",
  "tolower",
  "touper",
  "suma",
  "menos",
  "multi",
  "div",
  "xor",
  "printable",
  "modulo",
  "cadena",
  "caracter",
  "entero",
  "decimal",
  "booleano"
  };
}

