/* The following code was generated by JFlex 1.6.1 */

package Analisis;
import java_cup.runtime.Symbol;
import java.util.ArrayList;
import Analisis.lexema;
import Utilidades.ErrorC;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>scanner.jflex</tt>
 */
public class scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int cad1 = 2;
  public static final int cad2 = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
    18, 18, 18, 18, 18, 18, 18, 18, 18,  1,  3, 63,  1,  2, 18, 18, 
    18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
     1, 62, 10, 36, 18, 55, 45, 11, 56, 57, 12, 48, 50, 19,  5, 20, 
     4,  4,  4,  4,  4,  4,  4,  4,  4,  4, 17, 49, 51, 53, 52, 18, 
    18,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6, 
     6,  6, 47,  6,  6,  6,  6,  6,  6,  6,  6, 60, 18, 61, 54,  9, 
    18, 29, 34, 32, 31, 23, 22, 39, 33, 21,  6,  6, 24, 37, 30, 35, 
    38, 43, 27, 25, 26, 28, 42, 44, 41,  6, 40, 58, 46, 59, 18, 18, 
    18, 18, 18, 18, 18, 63, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
    18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
    18,  8, 18, 18, 18, 18, 18, 18, 18,  8, 18, 18, 18,  8, 18, 18, 
    18,  8, 18,  8, 18, 18, 18, 18, 18, 18,  8, 18, 18, 18, 18, 18, 
    18, 18, 18,  7, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
    18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
    18, 18, 13, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
    18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\1\4\1\5\1\6\1\1"+
    "\1\6\1\7\1\1\1\10\1\1\1\11\1\12\1\13"+
    "\12\6\1\1\2\6\2\1\1\6\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\2\0\10\6"+
    "\2\0\1\35\1\0\1\2\1\36\17\6\2\0\2\6"+
    "\1\37\1\40\1\6\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\13\6\1\47\1\6\1\50\4\0\1\2\2\6"+
    "\1\51\1\6\1\52\6\6\1\53\1\6\1\54\1\6"+
    "\1\55\1\56\2\0\1\57\3\6\1\60\12\6\1\61"+
    "\2\6\3\0\1\2\1\0\2\6\1\62\1\63\1\6"+
    "\1\64\4\6\1\65\2\0\1\6\1\66\1\6\1\67"+
    "\1\6\1\70\1\71\1\72\1\73\2\6\1\74\1\75"+
    "\2\6\3\0\1\2\1\6\1\76\6\6\2\0\1\77"+
    "\2\6\1\100\1\101\1\6\1\102\2\0\1\2\2\0"+
    "\1\103\1\104\1\6\1\105\1\6\1\106\1\6\2\0"+
    "\2\6\1\107\2\0\1\2\2\0\1\110\1\6\1\111"+
    "\2\0\1\112\1\6\2\0\1\113\1\0\1\114\1\115"+
    "\1\0\1\116\1\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[243];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\101\0\202\0\303\0\303\0\303\0\u0104\0\303"+
    "\0\u0145\0\u0186\0\u01c7\0\303\0\u0208\0\303\0\u0249\0\303"+
    "\0\u028a\0\u02cb\0\u030c\0\u034d\0\u038e\0\u03cf\0\u0410\0\u0451"+
    "\0\u0492\0\u04d3\0\u0514\0\u0555\0\u0596\0\u05d7\0\u0618\0\u0659"+
    "\0\u069a\0\u06db\0\u071c\0\303\0\303\0\u075d\0\u079e\0\u07df"+
    "\0\303\0\303\0\303\0\303\0\303\0\303\0\303\0\303"+
    "\0\303\0\303\0\303\0\u0820\0\u0186\0\u0861\0\u08a2\0\u08e3"+
    "\0\u0924\0\u0965\0\u09a6\0\u09e7\0\u0a28\0\u0a69\0\u0aaa\0\303"+
    "\0\u0aeb\0\u0b2c\0\u0145\0\u0b6d\0\u0bae\0\u0bef\0\u0c30\0\u0c71"+
    "\0\u0cb2\0\u0cf3\0\u0d34\0\u0d75\0\u0db6\0\u0df7\0\u0e38\0\u0e79"+
    "\0\u0eba\0\u0efb\0\u0f3c\0\u0f7d\0\u0fbe\0\u0fff\0\303\0\303"+
    "\0\u1040\0\303\0\303\0\303\0\303\0\303\0\u0820\0\u1081"+
    "\0\u10c2\0\u1103\0\u1144\0\u1185\0\u11c6\0\u1207\0\u1248\0\u1289"+
    "\0\u12ca\0\u130b\0\u0145\0\u134c\0\303\0\u138d\0\u13ce\0\u140f"+
    "\0\u1450\0\u1491\0\u14d2\0\u1513\0\u0145\0\u1554\0\u0145\0\u1595"+
    "\0\u15d6\0\u1617\0\u1658\0\u1699\0\u16da\0\u0145\0\u171b\0\u0145"+
    "\0\u175c\0\u0145\0\u0145\0\u179d\0\u17de\0\u0145\0\u181f\0\u1860"+
    "\0\u18a1\0\u0145\0\u18e2\0\u1923\0\u1964\0\u19a5\0\u19e6\0\u1a27"+
    "\0\u1a68\0\u1aa9\0\u1aea\0\u1b2b\0\u0145\0\u1b6c\0\u1bad\0\u1bee"+
    "\0\u1c2f\0\u1c70\0\u1cb1\0\u1cf2\0\u1d33\0\u1d74\0\u0145\0\u0145"+
    "\0\u1db5\0\u0145\0\u1df6\0\u1e37\0\u1e78\0\u1eb9\0\u0145\0\u1efa"+
    "\0\u1f3b\0\u1f7c\0\u0145\0\u1fbd\0\u0145\0\u1ffe\0\u0145\0\u0145"+
    "\0\u0145\0\u0145\0\u203f\0\u2080\0\u0145\0\u0145\0\u20c1\0\u2102"+
    "\0\u2143\0\u2184\0\u21c5\0\u2206\0\u2247\0\u0145\0\u2288\0\u22c9"+
    "\0\u230a\0\u234b\0\u238c\0\u23cd\0\u240e\0\u244f\0\u0145\0\u2490"+
    "\0\u24d1\0\u0145\0\u0145\0\u2512\0\u0145\0\u2553\0\u2594\0\u25d5"+
    "\0\u2616\0\u2657\0\u0145\0\u0145\0\u2698\0\u0145\0\u26d9\0\u0145"+
    "\0\u271a\0\u275b\0\u279c\0\u27dd\0\u281e\0\u0145\0\u25d5\0\u285f"+
    "\0\u28a0\0\u28e1\0\u2206\0\u0145\0\u2922\0\u0145\0\u2963\0\u29a4"+
    "\0\u0145\0\u29e5\0\u2a26\0\u2a67\0\u0145\0\u2aa8\0\303\0\u0145"+
    "\0\u2ae9\0\303\0\u28a0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[243];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\2\5\1\6\1\7\1\10\1\11\1\12\1\4"+
    "\1\13\1\14\1\15\1\16\1\17\3\4\1\20\1\4"+
    "\1\21\1\22\1\23\1\24\1\25\1\11\1\26\1\27"+
    "\1\30\2\11\1\31\1\32\1\33\1\11\1\34\1\11"+
    "\1\35\3\11\1\36\3\11\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\56\1\57\1\60\1\61\3\0"+
    "\15\62\3\0\57\62\2\0\15\63\3\0\57\63\106\0"+
    "\1\7\1\64\77\0\1\11\1\0\1\11\1\65\1\0"+
    "\1\11\13\0\17\11\1\0\10\11\2\0\1\11\31\0"+
    "\1\11\74\0\1\11\1\0\1\11\1\65\1\0\1\11"+
    "\13\0\1\66\1\11\1\67\3\11\1\70\1\11\1\71"+
    "\2\11\1\72\3\11\1\0\1\73\1\74\5\11\1\75"+
    "\2\0\1\11\21\0\14\76\1\0\64\76\16\0\1\77"+
    "\105\0\1\100\71\0\1\101\7\0\1\102\60\0\1\11"+
    "\1\0\1\11\1\65\1\0\1\11\13\0\1\11\1\103"+
    "\15\11\1\0\10\11\2\0\1\11\25\0\1\11\1\0"+
    "\1\11\1\65\1\0\1\11\13\0\7\11\1\104\1\105"+
    "\5\11\1\106\1\0\10\11\2\0\1\11\25\0\1\11"+
    "\1\0\1\11\1\65\1\0\1\11\13\0\3\11\1\107"+
    "\5\11\1\110\5\11\1\0\10\11\2\0\1\11\25\0"+
    "\1\11\1\0\1\11\1\65\1\0\1\11\13\0\1\111"+
    "\16\11\1\0\7\11\1\112\2\0\1\11\25\0\1\11"+
    "\1\0\1\11\1\65\1\0\1\11\13\0\6\11\1\113"+
    "\10\11\1\0\10\11\2\0\1\11\25\0\1\11\1\0"+
    "\1\11\1\65\1\0\1\11\13\0\2\11\1\114\13\11"+
    "\1\115\1\0\10\11\2\0\1\11\25\0\1\11\1\0"+
    "\1\11\1\65\1\0\1\11\13\0\3\11\1\116\13\11"+
    "\1\0\10\11\2\0\1\11\25\0\1\11\1\0\1\11"+
    "\1\65\1\0\1\11\13\0\2\11\1\117\14\11\1\0"+
    "\10\11\2\0\1\11\25\0\1\11\1\0\1\11\1\65"+
    "\1\0\1\11\13\0\10\11\1\120\3\11\1\121\2\11"+
    "\1\0\10\11\2\0\1\11\25\0\1\11\1\0\1\11"+
    "\1\65\1\0\1\11\13\0\7\11\1\122\7\11\1\0"+
    "\10\11\2\0\1\11\46\0\1\123\11\0\1\124\45\0"+
    "\1\11\1\0\1\11\1\65\1\0\1\11\13\0\6\11"+
    "\1\125\10\11\1\0\10\11\2\0\1\11\25\0\1\11"+
    "\1\0\1\11\1\65\1\0\1\11\13\0\14\11\1\126"+
    "\2\11\1\0\10\11\2\0\1\11\76\0\1\127\101\0"+
    "\1\130\26\0\1\11\1\0\1\11\1\65\1\0\1\11"+
    "\13\0\4\11\1\131\12\11\1\0\10\11\2\0\1\11"+
    "\101\0\1\132\104\0\1\133\1\134\100\0\1\135\100\0"+
    "\1\136\17\0\1\137\100\0\1\11\1\0\1\11\1\65"+
    "\1\0\1\11\13\0\17\11\1\0\1\140\7\11\2\0"+
    "\1\11\25\0\1\11\1\0\1\11\1\65\1\0\1\11"+
    "\13\0\17\11\1\0\6\11\1\141\1\11\2\0\1\11"+
    "\25\0\1\11\1\0\1\11\1\65\1\0\1\11\13\0"+
    "\2\11\1\142\14\11\1\0\10\11\2\0\1\11\25\0"+
    "\1\11\1\0\1\11\1\65\1\0\1\11\13\0\2\11"+
    "\1\143\2\11\1\144\4\11\1\145\4\11\1\0\1\11"+
    "\1\146\6\11\2\0\1\11\25\0\1\11\1\0\1\11"+
    "\1\65\1\0\1\11\13\0\3\11\1\147\12\11\1\150"+
    "\1\0\10\11\2\0\1\11\25\0\1\11\1\0\1\11"+
    "\1\65\1\0\1\11\13\0\4\11\1\151\12\11\1\0"+
    "\10\11\2\0\1\11\25\0\1\11\1\0\1\11\1\65"+
    "\1\0\1\11\13\0\2\11\1\152\14\11\1\0\10\11"+
    "\2\0\1\11\25\0\1\11\1\0\1\11\1\65\1\0"+
    "\1\11\13\0\1\11\1\153\4\11\1\154\10\11\1\0"+
    "\10\11\2\0\1\11\21\0\13\76\1\155\65\76\17\0"+
    "\1\156\61\0\14\157\1\160\7\157\1\161\54\157\2\102"+
    "\1\162\1\5\75\102\4\0\1\11\1\0\1\11\1\65"+
    "\1\0\1\11\13\0\4\11\1\163\12\11\1\0\10\11"+
    "\2\0\1\11\25\0\1\11\1\0\1\11\1\65\1\0"+
    "\1\11\13\0\3\11\1\164\13\11\1\0\10\11\2\0"+
    "\1\11\25\0\1\11\1\0\1\11\1\65\1\0\1\11"+
    "\13\0\6\11\1\165\10\11\1\0\10\11\2\0\1\11"+
    "\25\0\1\11\1\0\1\11\1\65\1\0\1\11\13\0"+
    "\4\11\1\166\12\11\1\0\10\11\2\0\1\11\25\0"+
    "\1\11\1\0\1\11\1\65\1\0\1\11\13\0\5\11"+
    "\1\167\11\11\1\0\10\11\2\0\1\11\25\0\1\11"+
    "\1\0\1\11\1\65\1\0\1\11\13\0\17\11\1\0"+
    "\2\11\1\170\5\11\2\0\1\11\25\0\1\11\1\0"+
    "\1\11\1\65\1\0\1\11\13\0\1\171\16\11\1\0"+
    "\10\11\2\0\1\11\25\0\1\11\1\0\1\11\1\65"+
    "\1\0\1\11\13\0\7\11\1\172\7\11\1\0\10\11"+
    "\2\0\1\11\25\0\1\11\1\0\1\11\1\65\1\0"+
    "\1\11\13\0\17\11\1\0\1\11\1\173\1\174\5\11"+
    "\2\0\1\11\25\0\1\11\1\0\1\11\1\65\1\0"+
    "\1\11\13\0\17\11\1\0\1\175\7\11\2\0\1\11"+
    "\25\0\1\11\1\0\1\11\1\65\1\0\1\11\13\0"+
    "\16\11\1\176\1\0\10\11\2\0\1\11\25\0\1\11"+
    "\1\0\1\11\1\65\1\0\1\11\13\0\1\11\1\177"+
    "\11\11\1\200\3\11\1\0\10\11\2\0\1\11\25\0"+
    "\1\11\1\0\1\11\1\65\1\0\1\11\13\0\4\11"+
    "\1\201\12\11\1\0\10\11\2\0\1\11\25\0\1\11"+
    "\1\0\1\11\1\65\1\0\1\11\13\0\6\11\1\202"+
    "\10\11\1\0\10\11\2\0\1\11\25\0\1\11\1\0"+
    "\1\11\1\65\1\0\1\11\13\0\3\11\1\203\13\11"+
    "\1\0\10\11\2\0\1\11\66\0\1\204\62\0\1\205"+
    "\55\0\1\11\1\0\1\11\1\65\1\0\1\11\13\0"+
    "\16\11\1\206\1\0\10\11\2\0\1\11\25\0\1\11"+
    "\1\0\1\11\1\65\1\0\1\11\13\0\1\207\1\11"+
    "\1\210\14\11\1\0\10\11\2\0\1\11\25\0\1\11"+
    "\1\0\1\11\1\65\1\0\1\11\13\0\5\11\1\211"+
    "\11\11\1\0\10\11\2\0\1\11\25\0\1\11\1\0"+
    "\1\11\1\65\1\0\1\11\13\0\17\11\1\0\1\11"+
    "\1\212\6\11\2\0\1\11\25\0\1\11\1\0\1\11"+
    "\1\65\1\0\1\11\13\0\3\11\1\213\13\11\1\0"+
    "\10\11\2\0\1\11\25\0\1\11\1\0\1\11\1\65"+
    "\1\0\1\11\13\0\4\11\1\214\3\11\1\215\6\11"+
    "\1\0\10\11\2\0\1\11\25\0\1\11\1\0\1\11"+
    "\1\65\1\0\1\11\13\0\11\11\1\216\5\11\1\0"+
    "\10\11\2\0\1\11\25\0\1\11\1\0\1\11\1\65"+
    "\1\0\1\11\13\0\17\11\1\0\4\11\1\217\3\11"+
    "\2\0\1\11\25\0\1\11\1\0\1\11\1\65\1\0"+
    "\1\11\13\0\2\11\1\220\14\11\1\0\10\11\2\0"+
    "\1\11\25\0\1\11\1\0\1\11\1\65\1\0\1\11"+
    "\13\0\2\11\1\221\14\11\1\0\10\11\2\0\1\11"+
    "\25\0\1\11\1\0\1\11\1\65\1\0\1\11\13\0"+
    "\16\11\1\222\1\0\10\11\2\0\1\11\25\0\1\11"+
    "\1\0\1\11\1\65\1\0\1\11\13\0\11\11\1\223"+
    "\5\11\1\0\1\11\1\224\6\11\2\0\1\11\25\0"+
    "\1\11\1\0\1\11\1\65\1\0\1\11\13\0\11\11"+
    "\1\225\5\11\1\0\10\11\2\0\1\11\25\0\1\11"+
    "\1\0\1\11\1\65\1\0\1\11\13\0\4\11\1\226"+
    "\12\11\1\0\10\11\2\0\1\11\25\0\1\11\1\0"+
    "\1\11\1\65\1\0\1\11\13\0\1\227\16\11\1\0"+
    "\10\11\2\0\1\11\21\0\14\230\1\0\64\230\14\157"+
    "\1\231\64\157\14\232\1\231\7\232\1\233\54\232\14\157"+
    "\1\234\64\157\3\0\1\5\101\0\1\11\1\0\1\11"+
    "\1\65\1\0\1\11\13\0\1\235\16\11\1\0\10\11"+
    "\2\0\1\11\25\0\1\11\1\0\1\11\1\65\1\0"+
    "\1\11\13\0\4\11\1\236\12\11\1\0\10\11\2\0"+
    "\1\11\25\0\1\11\1\0\1\11\1\65\1\0\1\11"+
    "\13\0\2\11\1\237\14\11\1\0\10\11\2\0\1\11"+
    "\25\0\1\11\1\0\1\11\1\65\1\0\1\11\13\0"+
    "\10\11\1\240\6\11\1\0\10\11\2\0\1\11\25\0"+
    "\1\11\1\0\1\11\1\65\1\0\1\11\13\0\5\11"+
    "\1\241\11\11\1\0\10\11\2\0\1\11\25\0\1\11"+
    "\1\0\1\11\1\65\1\0\1\11\13\0\2\11\1\242"+
    "\14\11\1\0\10\11\2\0\1\11\25\0\1\11\1\0"+
    "\1\11\1\65\1\0\1\11\13\0\2\11\1\243\14\11"+
    "\1\0\10\11\2\0\1\11\25\0\1\11\1\0\1\11"+
    "\1\65\1\0\1\11\13\0\6\11\1\244\10\11\1\0"+
    "\10\11\2\0\1\11\25\0\1\11\1\0\1\11\1\65"+
    "\1\0\1\11\13\0\17\11\1\0\1\11\1\245\6\11"+
    "\2\0\1\11\25\0\1\11\1\0\1\11\1\65\1\0"+
    "\1\11\13\0\10\11\1\246\6\11\1\0\10\11\2\0"+
    "\1\11\25\0\1\11\1\0\1\11\1\65\1\0\1\11"+
    "\13\0\2\11\1\247\14\11\1\0\10\11\2\0\1\11"+
    "\67\0\1\250\60\0\1\251\56\0\1\11\1\0\1\11"+
    "\1\65\1\0\1\11\13\0\3\11\1\252\13\11\1\0"+
    "\10\11\2\0\1\11\25\0\1\11\1\0\1\11\1\65"+
    "\1\0\1\11\13\0\11\11\1\253\5\11\1\0\10\11"+
    "\2\0\1\11\25\0\1\11\1\0\1\11\1\65\1\0"+
    "\1\11\13\0\6\11\1\254\10\11\1\0\10\11\2\0"+
    "\1\11\25\0\1\11\1\0\1\11\1\65\1\0\1\11"+
    "\13\0\4\11\1\255\12\11\1\0\10\11\2\0\1\11"+
    "\25\0\1\11\1\0\1\11\1\65\1\0\1\11\13\0"+
    "\2\11\1\256\14\11\1\0\10\11\2\0\1\11\25\0"+
    "\1\11\1\0\1\11\1\65\1\0\1\11\13\0\12\11"+
    "\1\257\4\11\1\0\10\11\2\0\1\11\25\0\1\11"+
    "\1\0\1\11\1\65\1\0\1\11\13\0\5\11\1\260"+
    "\11\11\1\0\10\11\2\0\1\11\25\0\1\11\1\0"+
    "\1\11\1\65\1\0\1\11\13\0\5\11\1\261\11\11"+
    "\1\0\10\11\2\0\1\11\25\0\1\11\1\0\1\11"+
    "\1\65\1\0\1\11\13\0\13\11\1\262\3\11\1\0"+
    "\10\11\2\0\1\11\25\0\1\11\1\0\1\11\1\65"+
    "\1\0\1\11\13\0\11\11\1\263\5\11\1\0\10\11"+
    "\2\0\1\11\25\0\1\11\1\0\1\11\1\65\1\0"+
    "\1\11\13\0\4\11\1\264\12\11\1\0\10\11\2\0"+
    "\1\11\25\0\1\11\1\0\1\11\1\65\1\0\1\11"+
    "\13\0\13\11\1\265\3\11\1\0\10\11\2\0\1\11"+
    "\25\0\1\11\1\0\1\11\1\65\1\0\1\11\13\0"+
    "\1\266\16\11\1\0\10\11\2\0\1\11\25\0\1\11"+
    "\1\0\1\11\1\65\1\0\1\11\13\0\16\11\1\267"+
    "\1\0\10\11\2\0\1\11\25\0\1\11\1\0\1\11"+
    "\1\65\1\0\1\11\13\0\5\11\1\270\11\11\1\0"+
    "\10\11\2\0\1\11\21\0\15\230\1\271\63\230\14\157"+
    "\1\231\7\157\1\5\54\157\14\232\1\272\64\232\14\157"+
    "\1\273\100\157\1\231\7\157\1\274\54\157\4\0\1\11"+
    "\1\0\1\11\1\65\1\0\1\11\13\0\16\11\1\275"+
    "\1\0\10\11\2\0\1\11\25\0\1\11\1\0\1\11"+
    "\1\65\1\0\1\11\13\0\2\11\1\276\14\11\1\0"+
    "\10\11\2\0\1\11\25\0\1\11\1\0\1\11\1\65"+
    "\1\0\1\11\13\0\13\11\1\277\3\11\1\0\10\11"+
    "\2\0\1\11\25\0\1\11\1\0\1\11\1\65\1\0"+
    "\1\11\13\0\5\11\1\300\2\11\1\301\6\11\1\0"+
    "\10\11\2\0\1\11\25\0\1\11\1\0\1\11\1\65"+
    "\1\0\1\11\13\0\2\11\1\302\14\11\1\0\10\11"+
    "\2\0\1\11\25\0\1\11\1\0\1\11\1\65\1\0"+
    "\1\11\13\0\2\11\1\303\14\11\1\0\10\11\2\0"+
    "\1\11\25\0\1\11\1\0\1\11\1\65\1\0\1\11"+
    "\13\0\7\11\1\304\7\11\1\0\10\11\2\0\1\11"+
    "\64\0\1\305\62\0\1\306\57\0\1\11\1\0\1\11"+
    "\1\65\1\0\1\11\13\0\2\11\1\307\14\11\1\0"+
    "\10\11\2\0\1\11\25\0\1\11\1\0\1\11\1\65"+
    "\1\0\1\11\13\0\1\310\16\11\1\0\10\11\2\0"+
    "\1\11\25\0\1\11\1\0\1\11\1\65\1\0\1\11"+
    "\13\0\6\11\1\311\10\11\1\0\10\11\2\0\1\11"+
    "\25\0\1\11\1\0\1\11\1\65\1\0\1\11\13\0"+
    "\12\11\1\312\4\11\1\0\10\11\2\0\1\11\25\0"+
    "\1\11\1\0\1\11\1\65\1\0\1\11\13\0\2\11"+
    "\1\313\14\11\1\0\10\11\2\0\1\11\25\0\1\11"+
    "\1\0\1\11\1\65\1\0\1\11\13\0\12\11\1\314"+
    "\4\11\1\0\10\11\2\0\1\11\25\0\1\11\1\0"+
    "\1\11\1\65\1\0\1\11\13\0\2\11\1\315\14\11"+
    "\1\0\10\11\2\0\1\11\21\0\15\230\1\271\1\316"+
    "\62\230\14\232\1\317\7\232\1\320\54\232\14\157\1\321"+
    "\7\157\1\5\54\157\14\0\1\322\70\0\1\11\1\0"+
    "\1\11\1\65\1\0\1\11\13\0\11\11\1\323\5\11"+
    "\1\0\10\11\2\0\1\11\25\0\1\11\1\0\1\11"+
    "\1\65\1\0\1\11\13\0\14\11\1\324\2\11\1\0"+
    "\10\11\2\0\1\11\25\0\1\11\1\0\1\11\1\65"+
    "\1\0\1\11\13\0\1\325\16\11\1\0\10\11\2\0"+
    "\1\11\25\0\1\11\1\0\1\11\1\65\1\0\1\11"+
    "\13\0\5\11\1\326\11\11\1\0\10\11\2\0\1\11"+
    "\25\0\1\11\1\0\1\11\1\65\1\0\1\11\13\0"+
    "\4\11\1\327\12\11\1\0\10\11\2\0\1\11\25\0"+
    "\1\11\1\0\1\11\1\65\1\0\1\11\13\0\6\11"+
    "\1\330\10\11\1\0\10\11\2\0\1\11\25\0\1\11"+
    "\1\0\1\11\1\65\1\0\1\11\13\0\3\11\1\331"+
    "\13\11\1\0\10\11\2\0\1\11\54\0\1\332\103\0"+
    "\1\333\46\0\1\11\1\0\1\11\1\65\1\0\1\11"+
    "\13\0\11\11\1\334\5\11\1\0\10\11\2\0\1\11"+
    "\25\0\1\11\1\0\1\11\1\65\1\0\1\11\13\0"+
    "\17\11\1\0\5\11\1\335\2\11\2\0\1\11\25\0"+
    "\1\11\1\0\1\11\1\65\1\0\1\11\13\0\2\11"+
    "\1\336\14\11\1\0\10\11\2\0\1\11\21\0\15\230"+
    "\1\271\2\230\1\155\60\230\14\232\1\317\7\232\1\5"+
    "\54\232\14\337\1\340\64\337\14\232\1\231\7\232\1\341"+
    "\54\232\14\0\1\342\7\0\1\343\60\0\1\11\1\0"+
    "\1\11\1\65\1\0\1\11\13\0\6\11\1\344\10\11"+
    "\1\0\10\11\2\0\1\11\25\0\1\11\1\0\1\11"+
    "\1\65\1\0\1\11\13\0\10\11\1\345\6\11\1\0"+
    "\10\11\2\0\1\11\25\0\1\11\1\0\1\11\1\65"+
    "\1\0\1\11\13\0\5\11\1\346\11\11\1\0\10\11"+
    "\2\0\1\11\53\0\1\347\73\0\1\350\57\0\1\11"+
    "\1\0\1\11\1\65\1\0\1\11\13\0\17\11\1\0"+
    "\2\11\1\351\5\11\2\0\1\11\25\0\1\11\1\0"+
    "\1\11\1\65\1\0\1\11\13\0\10\11\1\352\6\11"+
    "\1\0\10\11\2\0\1\11\21\0\14\337\1\353\64\337"+
    "\14\0\1\354\64\0\14\157\1\342\7\157\1\0\54\157"+
    "\4\0\1\11\1\0\1\11\1\65\1\0\1\11\13\0"+
    "\6\11\1\355\10\11\1\0\10\11\2\0\1\11\56\0"+
    "\1\356\76\0\1\357\51\0\1\11\1\0\1\11\1\65"+
    "\1\0\1\11\13\0\6\11\1\360\10\11\1\0\10\11"+
    "\2\0\1\11\21\0\14\337\1\353\7\337\1\5\54\337"+
    "\14\0\1\361\117\0\1\362\45\0\14\232\1\0\7\232"+
    "\1\363\54\232";

  private static int [] zzUnpackTrans() {
    int [] result = new int[11050];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\3\11\1\1\1\11\3\1\1\11\1\1\1\11"+
    "\1\1\1\11\23\1\2\11\3\1\13\11\2\0\10\1"+
    "\2\0\1\11\1\0\21\1\2\0\2\1\2\11\1\1"+
    "\5\11\16\1\1\11\4\0\22\1\2\0\22\1\3\0"+
    "\1\1\1\0\13\1\2\0\17\1\3\0\11\1\2\0"+
    "\7\1\2\0\1\1\2\0\7\1\2\0\3\1\2\0"+
    "\1\1\2\0\3\1\2\0\2\1\2\0\1\1\1\0"+
    "\1\11\1\1\1\0\1\11\1\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[243];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public ArrayList<ErrorC> listaErrores = new ArrayList(); // Lista para almacenar errores.
    public ArrayList<lexema> listaLexemas = new ArrayList(); // Lista para almacenar el flujo de palabras (tokens).
    public String cadena ="";
    public int linea=0,columna = 0;
    public void adderror(int linea, int columna, String valor)
    {        
        listaErrores.add(new ErrorC(ErrorC.TipoError.LEXICO,valor, linea, columna));
    }

    public void addLexema(String tipo, String valor, int linea, int columna)
    {        
        listaLexemas.add(new lexema(tipo, valor, linea, columna));	            
    } 
    public void Imprimir(String cadena)
    {
        System.out.println(cadena);
    }   
 



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scanner(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { 	return new Symbol(sym.EOF);    
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Caracter ilegal: " + yytext()+" Linea : "+yyline +" Columna: "+yychar); 
            adderror(yyline, yychar, yytext());
            }
          case 79: break;
          case 2: 
            { 
            }
          case 80: break;
          case 3: 
            { yychar=0;
            }
          case 81: break;
          case 4: 
            { addLexema("Identificador", yytext(), yyline, yychar);  	  
            if(Long.parseLong(yytext())> Utilidades.Singlenton.maxInt && Long.parseLong(yytext()) < Utilidades.Singlenton.minInt )
            {
                Utilidades.Singlenton.registrarError("Entero", "Número entero demasiado grande", ErrorC.TipoError.SEMANTICO,yyline, yychar);
                return new Symbol(sym.entero, yychar, yyline,0);             
            }   
            return new Symbol(sym.entero, yychar, yyline,Integer.parseInt(yytext()));
            }
          case 82: break;
          case 5: 
            { return new Symbol(sym.punto, yychar, yyline, yytext());
            }
          case 83: break;
          case 6: 
            { addLexema("Identificador", yytext(), yyline, yychar);  	        
            return new Symbol(sym.id, yychar, yyline, yytext().toLowerCase());
            }
          case 84: break;
          case 7: 
            { cadena = "";                    
            yybegin(cad1);
            linea = yyline;
            columna = yychar;
            }
          case 85: break;
          case 8: 
            { return new Symbol(sym.multi, yychar, yyline, yytext());
            }
          case 86: break;
          case 9: 
            { return new Symbol(sym.dospuntos, yychar, yyline, yytext());
            }
          case 87: break;
          case 10: 
            { return new Symbol(sym.menos, yychar, yyline, yytext());
            }
          case 88: break;
          case 11: 
            { return new Symbol(sym.div, yychar, yyline, yytext());
            }
          case 89: break;
          case 12: 
            { return new Symbol(sym.suma, yychar, yyline, yytext());
            }
          case 90: break;
          case 13: 
            { return new Symbol(sym.puntocoma, yychar, yyline, yytext());
            }
          case 91: break;
          case 14: 
            { return new Symbol(sym.coma, yychar, yyline, yytext());
            }
          case 92: break;
          case 15: 
            { return new Symbol(sym.menor, yychar, yyline, yytext());
            }
          case 93: break;
          case 16: 
            { return new Symbol(sym.mayor, yychar, yyline, yytext());
            }
          case 94: break;
          case 17: 
            { return new Symbol(sym.igual, yychar, yyline, yytext());
            }
          case 95: break;
          case 18: 
            { return new Symbol(sym.potencia, yychar, yyline, yytext());
            }
          case 96: break;
          case 19: 
            { return new Symbol(sym.modulo, yychar, yyline, yytext());
            }
          case 97: break;
          case 20: 
            { return new Symbol(sym.pari, yychar, yyline, yytext());
            }
          case 98: break;
          case 21: 
            { return new Symbol(sym.pard, yychar, yyline, yytext());
            }
          case 99: break;
          case 22: 
            { return new Symbol(sym.llavei, yychar, yyline, yytext());
            }
          case 100: break;
          case 23: 
            { return new Symbol(sym.llaved, yychar, yyline, yytext());
            }
          case 101: break;
          case 24: 
            { return new Symbol(sym.corchetei, yychar, yyline, yytext());
            }
          case 102: break;
          case 25: 
            { return new Symbol(sym.corcheted, yychar, yyline, yytext());
            }
          case 103: break;
          case 26: 
            { return new Symbol(sym.not, yychar, yyline, yytext());
            }
          case 104: break;
          case 27: 
            { switch(yytext())
        {
            case "\\":          
                yybegin(cad2);
            break;
            case "\"":      
                yybegin(YYINITIAL);
                return new Symbol(sym.cadena, columna, linea ,cadena);             
            default:
                cadena += yytext();
            break;                
        }
            }
          case 105: break;
          case 28: 
            { switch(yytext())
        {
            case "\'":
                cadena += "\'";
            break;            
            case "\"":
                cadena += "\"";
            break;  
            case "?":
                cadena += "?";
            case "%":
                cadena += "%";
            break;
            case "\\":
                cadena += "\\";
            break;  
            case "0":                
            break;  
            case "a":                
            break;   
            case "b":                
                cadena = cadena.substring(0, cadena.length()-1);
            break; 
            case "v":   
                String partes[] = cadena.split("\n");
                String subcadena = "";
                for(int i = 0 ; i < partes.length-1; i++)
                {
                    subcadena += partes[i];
                }         
                String tabulaciones[] = partes[partes.length].split("\t");
                for(int i = 0; i< tabulaciones.length; i++)
                {
                    subcadena += "\t";
                }
                cadena = subcadena;                                                       
            break;             
            case "n":                
                cadena = cadena + "\n";
            break; 
            case "t":                
                cadena = cadena + "\t";
            break;             
            case "r":       
                partes = cadena.split("\n");
                subcadena = "";
                for(int i = 0 ; i < partes.length-1; i++)
                {
                    subcadena += partes[i];
                }                                       
                cadena = subcadena;
            break;                                                                                                       
            default:
                cadena += "\\"+yytext();
                //Utilidades.Singlenton.registrarError("\\"+yytext(), "Carácter ilegal. Ha sido eliminado.", ErrorC.TipoError.SEMANTICO,yyline, yychar);
            break;                
        }
        yybegin(cad1);
            }
          case 106: break;
          case 29: 
            { return new Symbol(sym.decremento, yychar, yyline, yytext());
            }
          case 107: break;
          case 30: 
            { return new Symbol(sym.si, yychar, yyline, yytext());
            }
          case 108: break;
          case 31: 
            { return new Symbol(sym.and, yychar, yyline, yytext());
            }
          case 109: break;
          case 32: 
            { return new Symbol(sym.or, yychar, yyline, yytext());
            }
          case 110: break;
          case 33: 
            { return new Symbol(sym.aumento, yychar, yyline, yytext());
            }
          case 111: break;
          case 34: 
            { return new Symbol(sym.desigual, yychar, yyline, yytext());
            }
          case 112: break;
          case 35: 
            { return new Symbol(sym.menorigual, yychar, yyline, yytext());
            }
          case 113: break;
          case 36: 
            { return new Symbol(sym.mayorigual, yychar, yyline, yytext());
            }
          case 114: break;
          case 37: 
            { return new Symbol(sym.igualigual, yychar, yyline, yytext());
            }
          case 115: break;
          case 38: 
            { addLexema("Identificador", yytext(), yyline, yychar);  	        
            return new Symbol(sym.decimal, yychar, yyline,Double.parseDouble(yytext()));
            }
          case 116: break;
          case 39: 
            { return new Symbol(sym.escribir, yychar, yyline, yytext());
            }
          case 117: break;
          case 40: 
            { addLexema("Identificador", yytext(), yyline, yychar);  	        
            return new Symbol(sym.caracter, yychar, yyline,yytext().substring(1, yytext().length()-1).charAt(0));
            }
          case 118: break;
          case 41: 
            { return new Symbol(sym.para, yychar, yyline, yytext());
            }
          case 119: break;
          case 42: 
            { return new Symbol(sym.tint, yychar, yyline, yytext());
            }
          case 120: break;
          case 43: 
            { return new Symbol(sym.nulo, yychar, yyline, yytext());
            }
          case 121: break;
          case 44: 
            { return new Symbol(sym.tdouble, yychar, yyline, yytext());
            }
          case 122: break;
          case 45: 
            { return new Symbol(sym.tchar, yychar, yyline, yytext());
            }
          case 123: break;
          case 46: 
            { return new Symbol(sym.tbool, yychar, yyline, yytext());
            }
          case 124: break;
          case 47: 
            { return new Symbol(sym.tvoid, yychar, yyline, yytext());
            }
          case 125: break;
          case 48: 
            { return new Symbol(sym.print, yychar, yyline, yytext());
            }
          case 126: break;
          case 49: 
            { return new Symbol(sym.msn, yychar, yyline, yytext());
            }
          case 127: break;
          case 50: 
            { return new Symbol(sym.sino, yychar, yyline, yytext());
            }
          case 128: break;
          case 51: 
            { return new Symbol(sym.continuar, yychar, yyline, yytext());
            }
          case 129: break;
          case 52: 
            { return new Symbol(sym.booleano,yychar, yyline, true);
            }
          case 130: break;
          case 53: 
            { return new Symbol(sym.caso, yychar, yyline, yytext());
            }
          case 131: break;
          case 54: 
            { return new Symbol(sym.donde, yychar, yyline, yytext());
            }
          case 132: break;
          case 55: 
            { return new Symbol(sym.teql, yychar, yyline, yytext());
            }
          case 133: break;
          case 56: 
            { return new Symbol(sym.tread, yychar, yyline, yytext());
            }
          case 134: break;
          case 57: 
            { return new Symbol(sym.taentero, yychar, yyline, yytext());
            }
          case 135: break;
          case 58: 
            { return new Symbol(sym.tatexto, yychar, yyline, yytext());
            }
          case 136: break;
          case 59: 
            { return new Symbol(sym.tadecimal, yychar, yyline, yytext());
            }
          case 137: break;
          case 60: 
            { return new Symbol(sym.tconcatenar, yychar, yyline, yytext());
            }
          case 138: break;
          case 61: 
            { return new Symbol(sym.tcopi, yychar, yyline, yytext());
            }
          case 139: break;
          case 62: 
            { return new Symbol(sym.booleano,yychar, yyline, false);
            }
          case 140: break;
          case 63: 
            { return new Symbol(sym.mientras, yychar, yyline, yytext());
            }
          case 141: break;
          case 64: 
            { return new Symbol(sym.tapend, yychar, yyline, yytext());
            }
          case 142: break;
          case 65: 
            { return new Symbol(sym.tclose, yychar, yyline, yytext());
            }
          case 143: break;
          case 66: 
            { return new Symbol(sym.escritura, yychar, yyline, yytext());
            }
          case 144: break;
          case 67: 
            { return new Symbol(sym.tfusion, yychar, yyline, yytext());
            }
          case 145: break;
          case 68: 
            { return new Symbol(sym.switch_, yychar, yyline, yytext());
            }
          case 146: break;
          case 69: 
            { return new Symbol(sym.hacer, yychar, yyline, yytext());
            }
          case 147: break;
          case 70: 
            { return new Symbol(sym.romper, yychar, yyline, yytext());
            }
          case 148: break;
          case 71: 
            { return new Symbol(sym.tpeso, yychar, yyline, yytext());
            }
          case 149: break;
          case 72: 
            { return new Symbol(sym.repetir, yychar, yyline, yytext());
            }
          case 150: break;
          case 73: 
            { return new Symbol(sym.defecto, yychar, yyline, yytext());
            }
          case 151: break;
          case 74: 
            { return new Symbol(sym.tstring, yychar, yyline, yytext());
            }
          case 152: break;
          case 75: 
            { return new Symbol(sym.retorno, yychar, yyline, yytext());
            }
          case 153: break;
          case 76: 
            { return new Symbol(sym.tdefinir, yychar, yyline, yytext());
            }
          case 154: break;
          case 77: 
            { return new Symbol(sym.treservar, yychar, yyline, yytext());
            }
          case 155: break;
          case 78: 
            { return new Symbol(sym.importar, yychar, yyline, yytext());
            }
          case 156: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
