/* The following code was generated by JFlex 1.6.1 */

package Analisis;
import java_cup.runtime.Symbol;
import java.util.ArrayList;
import Analisis.lexema;
import Utilidades.ErrorC;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>scanner.jflex</tt>
 */
public class scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int cad1 = 2;
  public static final int cad2 = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
    18, 18, 18, 18, 18, 18, 18, 18, 18,  1,  3, 72,  1,  2, 18, 18, 
    18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
     1, 71, 10, 36, 18, 64, 45, 11, 65, 66, 12, 57, 59, 19,  5, 20, 
     4,  4,  4,  4,  4,  4,  4,  4,  4,  4, 17, 58, 60, 62, 61, 18, 
    18, 56,  6,  6,  6,  6,  6, 51,  6, 53,  6,  6,  6,  6, 50,  6, 
    55,  6, 47,  6,  6, 52,  6,  6,  6,  6,  6, 69, 18, 70, 63,  9, 
    18, 29, 34, 32, 31, 23, 22, 39, 33, 21, 48, 49, 24, 37, 30, 35, 
    38, 43, 27, 25, 26, 28, 42, 44, 41, 54, 40, 67, 46, 68, 18, 18, 
    18, 18, 18, 18, 18, 72, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
    18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
    18,  8, 18, 18, 18, 18, 18, 18, 18,  8, 18, 18, 18,  8, 18, 18, 
    18,  8, 18,  8, 18, 18, 18, 18, 18, 18,  8, 18, 18, 18, 18, 18, 
    18, 18, 18,  7, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
    18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
    18, 18, 13, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
    18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\1\2\1\3\1\4\1\5\1\6\1\1"+
    "\1\6\1\7\1\1\1\10\1\1\1\11\1\12\1\13"+
    "\13\6\1\1\2\6\2\1\1\6\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\2\0\11\6"+
    "\2\0\1\35\1\0\1\2\1\36\21\6\2\0\2\6"+
    "\1\37\1\40\5\6\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\15\6\1\47\2\6\1\50\4\0\1\2\3\6"+
    "\1\51\1\6\1\52\7\6\1\53\1\6\1\54\1\6"+
    "\1\55\1\56\2\0\1\57\7\6\1\60\14\6\1\61"+
    "\3\6\3\0\1\2\1\0\3\6\1\62\1\63\1\6"+
    "\1\64\5\6\1\65\2\0\1\6\1\66\1\67\1\6"+
    "\1\70\2\6\1\71\1\6\1\72\1\73\1\6\1\74"+
    "\1\75\3\6\1\76\1\77\3\6\3\0\1\2\2\6"+
    "\1\100\7\6\2\0\1\101\1\6\1\102\1\103\1\104"+
    "\5\6\1\105\1\106\1\6\1\107\1\6\2\0\1\2"+
    "\2\0\1\6\1\110\1\111\1\6\1\112\1\6\1\113"+
    "\2\6\2\0\1\6\1\114\4\6\1\115\1\6\2\0"+
    "\1\2\2\0\1\6\1\116\2\6\1\117\2\0\1\120"+
    "\5\6\2\0\1\6\1\121\1\6\1\0\1\122\1\123"+
    "\1\124\3\6\1\0\2\6\1\125\2\6\1\126\1\0"+
    "\11\6\1\127\1\130\2\6\1\131\1\6\1\132";

  private static int [] zzUnpackAction() {
    int [] result = new int[322];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\112\0\224\0\336\0\336\0\336\0\u0128\0\336"+
    "\0\u0172\0\u01bc\0\u0206\0\336\0\u0250\0\336\0\u029a\0\336"+
    "\0\u02e4\0\u032e\0\u0378\0\u03c2\0\u040c\0\u0456\0\u04a0\0\u04ea"+
    "\0\u0534\0\u057e\0\u05c8\0\u0612\0\u065c\0\u06a6\0\u06f0\0\u073a"+
    "\0\u0784\0\u07ce\0\u0818\0\u0862\0\336\0\336\0\u08ac\0\u08f6"+
    "\0\u0940\0\336\0\336\0\336\0\336\0\336\0\336\0\336"+
    "\0\336\0\336\0\336\0\336\0\u098a\0\u01bc\0\u09d4\0\u0a1e"+
    "\0\u0a68\0\u0ab2\0\u0afc\0\u0b46\0\u0b90\0\u0bda\0\u0c24\0\u0c6e"+
    "\0\u0cb8\0\336\0\u0d02\0\u0d4c\0\u0172\0\u0d96\0\u0de0\0\u0e2a"+
    "\0\u0e74\0\u0ebe\0\u0f08\0\u0f52\0\u0f9c\0\u0fe6\0\u1030\0\u107a"+
    "\0\u10c4\0\u110e\0\u1158\0\u11a2\0\u11ec\0\u1236\0\u1280\0\u12ca"+
    "\0\u1314\0\u135e\0\336\0\336\0\u13a8\0\u13f2\0\u143c\0\u1486"+
    "\0\u14d0\0\336\0\336\0\336\0\336\0\336\0\u098a\0\u151a"+
    "\0\u1564\0\u15ae\0\u15f8\0\u1642\0\u168c\0\u16d6\0\u1720\0\u176a"+
    "\0\u17b4\0\u17fe\0\u1848\0\u1892\0\u0172\0\u18dc\0\u1926\0\336"+
    "\0\u1970\0\u19ba\0\u1a04\0\u1a4e\0\u1a98\0\u1ae2\0\u1b2c\0\u1b76"+
    "\0\u0172\0\u1bc0\0\u0172\0\u1c0a\0\u1c54\0\u1c9e\0\u1ce8\0\u1d32"+
    "\0\u1d7c\0\u1dc6\0\u0172\0\u1e10\0\u0172\0\u1e5a\0\u0172\0\u0172"+
    "\0\u1ea4\0\u1eee\0\u0172\0\u1f38\0\u1f82\0\u1fcc\0\u2016\0\u2060"+
    "\0\u20aa\0\u20f4\0\u0172\0\u213e\0\u2188\0\u21d2\0\u221c\0\u2266"+
    "\0\u22b0\0\u22fa\0\u2344\0\u238e\0\u23d8\0\u2422\0\u246c\0\u0172"+
    "\0\u24b6\0\u2500\0\u254a\0\u2594\0\u25de\0\u2628\0\u2672\0\u26bc"+
    "\0\u2706\0\u2750\0\u279a\0\u0172\0\u0172\0\u27e4\0\u0172\0\u282e"+
    "\0\u2878\0\u28c2\0\u290c\0\u2956\0\u0172\0\u29a0\0\u29ea\0\u2a34"+
    "\0\u0172\0\u0172\0\u2a7e\0\u2ac8\0\u2b12\0\u2b5c\0\u0172\0\u2ba6"+
    "\0\u0172\0\u0172\0\u2bf0\0\u0172\0\u0172\0\u2c3a\0\u2c84\0\u2cce"+
    "\0\u0172\0\u0172\0\u2d18\0\u2d62\0\u2dac\0\u2df6\0\u2e40\0\u2e8a"+
    "\0\u2ed4\0\u2f1e\0\u2f68\0\u0172\0\u2fb2\0\u2ffc\0\u3046\0\u3090"+
    "\0\u30da\0\u3124\0\u316e\0\u31b8\0\u3202\0\u0172\0\u324c\0\u0172"+
    "\0\u0172\0\u0172\0\u3296\0\u32e0\0\u332a\0\u3374\0\u33be\0\u0172"+
    "\0\u0172\0\u3408\0\u0172\0\u3452\0\u349c\0\u34e6\0\u3530\0\u357a"+
    "\0\u35c4\0\u360e\0\u0172\0\u0172\0\u3658\0\u0172\0\u36a2\0\u0172"+
    "\0\u36ec\0\u3736\0\u3780\0\u37ca\0\u3814\0\u0172\0\u385e\0\u38a8"+
    "\0\u38f2\0\u393c\0\u0172\0\u3986\0\u3530\0\u39d0\0\u3a1a\0\u3a64"+
    "\0\u2ed4\0\u3aae\0\u0172\0\u3af8\0\u3b42\0\u0172\0\u3b8c\0\u3bd6"+
    "\0\u0172\0\u3c20\0\u3c6a\0\u3cb4\0\u3cfe\0\u3d48\0\u3d92\0\u3ddc"+
    "\0\u3e26\0\u0172\0\u3e70\0\u3eba\0\336\0\u0172\0\u0172\0\u3f04"+
    "\0\u3f4e\0\u3f98\0\u3fe2\0\u402c\0\u4076\0\336\0\u40c0\0\u410a"+
    "\0\u0172\0\u3a1a\0\u4154\0\u419e\0\u41e8\0\u4232\0\u427c\0\u42c6"+
    "\0\u4310\0\u435a\0\u43a4\0\u0172\0\u0172\0\u43ee\0\u4438\0\u0172"+
    "\0\u4482\0\u0172";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[322];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\2\5\1\6\1\7\1\10\1\11\1\12\1\4"+
    "\1\13\1\14\1\15\1\16\1\17\3\4\1\20\1\4"+
    "\1\21\1\22\1\23\1\24\1\25\1\11\1\26\1\27"+
    "\1\30\1\11\1\31\1\32\1\33\1\34\1\11\1\35"+
    "\1\11\1\36\3\11\1\37\3\11\1\40\1\41\1\42"+
    "\1\43\11\11\1\44\1\45\1\46\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\1\55\1\56\1\57\1\60\1\61"+
    "\1\62\3\0\15\63\3\0\70\63\2\0\15\64\3\0"+
    "\70\64\117\0\1\7\1\65\110\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\13\0\17\11\1\0\10\11\2\0"+
    "\12\11\31\0\1\11\105\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\13\0\1\67\1\11\1\70\3\11\1\71"+
    "\1\11\1\72\2\11\1\73\3\11\1\0\1\74\1\75"+
    "\5\11\1\76\2\0\3\11\1\77\6\11\21\0\14\100"+
    "\1\0\75\100\16\0\1\101\116\0\1\102\102\0\1\103"+
    "\7\0\1\104\71\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\13\0\1\11\1\105\7\11\1\106\5\11\1\0"+
    "\10\11\2\0\12\11\25\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\13\0\7\11\1\107\1\110\5\11\1\111"+
    "\1\0\10\11\2\0\12\11\25\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\13\0\3\11\1\112\5\11\1\113"+
    "\5\11\1\0\10\11\2\0\12\11\25\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\13\0\1\114\16\11\1\0"+
    "\7\11\1\115\2\0\12\11\25\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\13\0\6\11\1\116\10\11\1\0"+
    "\10\11\2\0\12\11\25\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\13\0\2\11\1\117\13\11\1\120\1\0"+
    "\10\11\2\0\12\11\25\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\13\0\3\11\1\121\13\11\1\0\10\11"+
    "\2\0\12\11\25\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\13\0\3\11\1\122\13\11\1\0\10\11\2\0"+
    "\12\11\25\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\13\0\2\11\1\123\14\11\1\0\10\11\2\0\12\11"+
    "\25\0\1\11\1\0\1\11\1\66\1\0\1\11\13\0"+
    "\10\11\1\124\3\11\1\125\2\11\1\0\10\11\2\0"+
    "\12\11\25\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\13\0\7\11\1\126\7\11\1\0\10\11\2\0\12\11"+
    "\46\0\1\127\11\0\1\130\56\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\13\0\6\11\1\131\10\11\1\0"+
    "\10\11\2\0\12\11\25\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\13\0\14\11\1\132\2\11\1\0\10\11"+
    "\2\0\12\11\76\0\1\133\112\0\1\134\37\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\13\0\3\11\1\135"+
    "\1\136\1\137\7\11\1\140\1\11\1\0\1\141\7\11"+
    "\2\0\12\11\112\0\1\142\115\0\1\143\1\144\111\0"+
    "\1\145\111\0\1\146\17\0\1\147\111\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\13\0\17\11\1\0\1\150"+
    "\7\11\2\0\12\11\25\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\13\0\17\11\1\0\6\11\1\151\1\11"+
    "\2\0\12\11\25\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\13\0\2\11\1\152\14\11\1\0\10\11\2\0"+
    "\12\11\25\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\13\0\2\11\1\153\1\154\1\11\1\155\4\11\1\156"+
    "\2\11\1\157\1\11\1\0\1\11\1\160\6\11\2\0"+
    "\12\11\25\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\13\0\3\11\1\161\12\11\1\162\1\0\10\11\2\0"+
    "\12\11\25\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\13\0\4\11\1\163\12\11\1\0\10\11\2\0\12\11"+
    "\25\0\1\11\1\0\1\11\1\66\1\0\1\11\13\0"+
    "\2\11\1\164\14\11\1\0\10\11\2\0\12\11\25\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\13\0\1\11"+
    "\1\165\4\11\1\166\10\11\1\0\10\11\2\0\12\11"+
    "\25\0\1\11\1\0\1\11\1\66\1\0\1\11\13\0"+
    "\7\11\1\167\7\11\1\0\10\11\2\0\12\11\21\0"+
    "\13\100\1\170\76\100\17\0\1\171\72\0\14\172\1\173"+
    "\7\172\1\174\65\172\2\104\1\175\1\5\106\104\4\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\13\0\1\176"+
    "\16\11\1\0\10\11\2\0\12\11\25\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\13\0\4\11\1\177\12\11"+
    "\1\0\10\11\2\0\12\11\25\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\13\0\3\11\1\200\13\11\1\0"+
    "\10\11\2\0\12\11\25\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\13\0\6\11\1\201\10\11\1\0\10\11"+
    "\2\0\12\11\25\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\13\0\4\11\1\202\12\11\1\0\10\11\2\0"+
    "\12\11\25\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\13\0\5\11\1\203\11\11\1\0\10\11\2\0\12\11"+
    "\25\0\1\11\1\0\1\11\1\66\1\0\1\11\13\0"+
    "\17\11\1\0\2\11\1\204\5\11\2\0\12\11\25\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\13\0\1\205"+
    "\16\11\1\0\10\11\2\0\12\11\25\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\13\0\7\11\1\206\7\11"+
    "\1\0\10\11\2\0\12\11\25\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\13\0\17\11\1\0\1\11\1\207"+
    "\1\210\5\11\2\0\12\11\25\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\13\0\17\11\1\0\1\211\7\11"+
    "\2\0\12\11\25\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\212\13\0\17\11\1\0\10\11\2\0\12\11\25\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\13\0\16\11"+
    "\1\213\1\0\10\11\2\0\12\11\25\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\13\0\1\11\1\214\11\11"+
    "\1\215\3\11\1\0\10\11\2\0\12\11\25\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\13\0\4\11\1\216"+
    "\12\11\1\0\10\11\2\0\12\11\25\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\13\0\6\11\1\217\10\11"+
    "\1\0\10\11\2\0\12\11\25\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\13\0\3\11\1\220\13\11\1\0"+
    "\10\11\2\0\12\11\66\0\1\221\73\0\1\222\66\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\13\0\16\11"+
    "\1\223\1\0\10\11\2\0\12\11\25\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\13\0\1\224\1\11\1\225"+
    "\14\11\1\0\10\11\2\0\12\11\25\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\13\0\15\11\1\226\1\11"+
    "\1\0\10\11\2\0\12\11\25\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\13\0\5\11\1\227\11\11\1\0"+
    "\10\11\2\0\12\11\25\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\13\0\17\11\1\0\4\11\1\230\3\11"+
    "\2\0\12\11\25\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\13\0\16\11\1\231\1\0\10\11\2\0\12\11"+
    "\25\0\1\11\1\0\1\11\1\66\1\0\1\11\13\0"+
    "\2\11\1\232\14\11\1\0\10\11\2\0\12\11\25\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\13\0\17\11"+
    "\1\0\1\11\1\233\6\11\2\0\12\11\25\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\13\0\3\11\1\234"+
    "\13\11\1\0\10\11\2\0\12\11\25\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\13\0\4\11\1\235\3\11"+
    "\1\236\6\11\1\0\10\11\2\0\12\11\25\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\13\0\11\11\1\237"+
    "\5\11\1\0\10\11\2\0\12\11\25\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\13\0\5\11\1\240\11\11"+
    "\1\0\10\11\2\0\12\11\25\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\13\0\17\11\1\0\4\11\1\241"+
    "\3\11\2\0\12\11\25\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\13\0\2\11\1\242\14\11\1\0\10\11"+
    "\2\0\12\11\25\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\13\0\6\11\1\243\10\11\1\0\10\11\2\0"+
    "\12\11\25\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\13\0\2\11\1\244\14\11\1\0\10\11\2\0\12\11"+
    "\25\0\1\11\1\0\1\11\1\66\1\0\1\11\13\0"+
    "\16\11\1\245\1\0\10\11\2\0\12\11\25\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\13\0\11\11\1\246"+
    "\5\11\1\0\1\11\1\247\6\11\2\0\12\11\25\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\13\0\11\11"+
    "\1\250\5\11\1\0\10\11\2\0\12\11\25\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\13\0\4\11\1\251"+
    "\12\11\1\0\10\11\2\0\12\11\25\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\13\0\1\252\16\11\1\0"+
    "\10\11\2\0\12\11\25\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\13\0\2\11\1\253\14\11\1\0\10\11"+
    "\2\0\12\11\21\0\14\254\1\0\75\254\14\172\1\255"+
    "\75\172\14\256\1\255\7\256\1\257\65\256\14\172\1\260"+
    "\75\172\3\0\1\5\112\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\13\0\13\11\1\261\3\11\1\0\10\11"+
    "\2\0\12\11\25\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\13\0\1\262\16\11\1\0\10\11\2\0\12\11"+
    "\25\0\1\11\1\0\1\11\1\66\1\0\1\11\13\0"+
    "\4\11\1\263\12\11\1\0\10\11\2\0\12\11\25\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\13\0\2\11"+
    "\1\264\14\11\1\0\10\11\2\0\12\11\25\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\13\0\10\11\1\265"+
    "\6\11\1\0\10\11\2\0\12\11\25\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\13\0\5\11\1\266\11\11"+
    "\1\0\10\11\2\0\12\11\25\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\13\0\2\11\1\267\14\11\1\0"+
    "\10\11\2\0\12\11\25\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\13\0\2\11\1\270\14\11\1\0\10\11"+
    "\2\0\12\11\25\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\13\0\6\11\1\271\10\11\1\0\10\11\2\0"+
    "\12\11\25\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\13\0\17\11\1\0\1\11\1\272\6\11\2\0\12\11"+
    "\25\0\1\11\1\0\1\11\1\66\1\0\1\11\13\0"+
    "\12\11\1\273\4\11\1\0\10\11\2\0\12\11\25\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\13\0\10\11"+
    "\1\274\6\11\1\0\10\11\2\0\12\11\25\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\13\0\2\11\1\275"+
    "\14\11\1\0\10\11\2\0\12\11\67\0\1\276\71\0"+
    "\1\277\67\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\13\0\3\11\1\300\13\11\1\0\10\11\2\0\12\11"+
    "\25\0\1\11\1\0\1\11\1\66\1\0\1\11\13\0"+
    "\11\11\1\301\5\11\1\0\10\11\2\0\12\11\25\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\13\0\3\11"+
    "\1\302\13\11\1\0\10\11\2\0\12\11\25\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\13\0\6\11\1\303"+
    "\10\11\1\0\10\11\2\0\12\11\25\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\13\0\5\11\1\304\11\11"+
    "\1\0\10\11\2\0\12\11\25\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\13\0\5\11\1\305\11\11\1\0"+
    "\10\11\2\0\12\11\25\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\13\0\11\11\1\306\5\11\1\0\10\11"+
    "\2\0\12\11\25\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\13\0\4\11\1\307\12\11\1\0\10\11\2\0"+
    "\12\11\25\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\13\0\2\11\1\310\14\11\1\0\10\11\2\0\12\11"+
    "\25\0\1\11\1\0\1\11\1\66\1\0\1\11\13\0"+
    "\12\11\1\311\4\11\1\0\10\11\2\0\12\11\25\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\13\0\5\11"+
    "\1\312\11\11\1\0\10\11\2\0\12\11\25\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\13\0\16\11\1\313"+
    "\1\0\10\11\2\0\12\11\25\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\13\0\5\11\1\314\11\11\1\0"+
    "\10\11\2\0\12\11\25\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\13\0\13\11\1\315\3\11\1\0\10\11"+
    "\2\0\12\11\25\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\13\0\1\316\16\11\1\0\10\11\2\0\12\11"+
    "\25\0\1\11\1\0\1\11\1\66\1\0\1\11\13\0"+
    "\11\11\1\317\5\11\1\0\10\11\2\0\12\11\25\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\13\0\4\11"+
    "\1\320\12\11\1\0\10\11\2\0\12\11\25\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\13\0\13\11\1\321"+
    "\3\11\1\0\10\11\2\0\12\11\25\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\13\0\1\322\16\11\1\0"+
    "\10\11\2\0\12\11\25\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\13\0\16\11\1\323\1\0\10\11\2\0"+
    "\12\11\25\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\13\0\5\11\1\324\11\11\1\0\10\11\2\0\12\11"+
    "\25\0\1\11\1\0\1\11\1\66\1\0\1\11\13\0"+
    "\17\11\1\0\5\11\1\325\2\11\2\0\12\11\21\0"+
    "\15\254\1\326\74\254\14\172\1\255\7\172\1\5\65\172"+
    "\14\256\1\327\75\256\14\172\1\330\111\172\1\255\7\172"+
    "\1\331\65\172\4\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\13\0\1\332\16\11\1\0\10\11\2\0\12\11"+
    "\25\0\1\11\1\0\1\11\1\66\1\0\1\11\13\0"+
    "\16\11\1\333\1\0\10\11\2\0\12\11\25\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\13\0\2\11\1\334"+
    "\14\11\1\0\10\11\2\0\12\11\25\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\13\0\13\11\1\335\3\11"+
    "\1\0\10\11\2\0\12\11\25\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\13\0\5\11\1\336\2\11\1\337"+
    "\6\11\1\0\10\11\2\0\12\11\25\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\13\0\2\11\1\340\14\11"+
    "\1\0\10\11\2\0\12\11\25\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\13\0\2\11\1\341\14\11\1\0"+
    "\10\11\2\0\12\11\25\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\13\0\10\11\1\342\6\11\1\0\10\11"+
    "\2\0\12\11\25\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\13\0\7\11\1\343\7\11\1\0\10\11\2\0"+
    "\12\11\64\0\1\344\73\0\1\345\70\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\13\0\2\11\1\346\14\11"+
    "\1\0\10\11\2\0\12\11\25\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\13\0\1\347\16\11\1\0\10\11"+
    "\2\0\12\11\25\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\13\0\17\11\1\0\10\11\2\0\3\11\1\350"+
    "\4\11\1\351\1\352\25\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\13\0\16\11\1\353\1\0\10\11\2\0"+
    "\12\11\25\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\13\0\4\11\1\354\12\11\1\0\10\11\2\0\12\11"+
    "\25\0\1\11\1\0\1\11\1\66\1\0\1\11\13\0"+
    "\6\11\1\355\10\11\1\0\10\11\2\0\12\11\25\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\356\13\0\17\11"+
    "\1\0\10\11\2\0\12\11\25\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\13\0\6\11\1\357\10\11\1\0"+
    "\10\11\2\0\12\11\25\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\13\0\12\11\1\360\4\11\1\0\10\11"+
    "\2\0\12\11\25\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\13\0\2\11\1\361\14\11\1\0\10\11\2\0"+
    "\12\11\25\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\13\0\12\11\1\362\4\11\1\0\10\11\2\0\12\11"+
    "\25\0\1\11\1\0\1\11\1\66\1\0\1\11\13\0"+
    "\2\11\1\363\14\11\1\0\10\11\2\0\12\11\25\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\13\0\16\11"+
    "\1\364\1\0\10\11\2\0\12\11\21\0\15\254\1\326"+
    "\1\365\73\254\14\256\1\366\7\256\1\367\65\256\14\172"+
    "\1\370\7\172\1\5\65\172\14\0\1\371\101\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\13\0\10\11\1\372"+
    "\6\11\1\0\10\11\2\0\12\11\25\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\13\0\11\11\1\373\5\11"+
    "\1\0\10\11\2\0\12\11\25\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\13\0\14\11\1\374\2\11\1\0"+
    "\10\11\2\0\12\11\25\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\13\0\1\375\16\11\1\0\10\11\2\0"+
    "\12\11\25\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\13\0\5\11\1\376\11\11\1\0\10\11\2\0\12\11"+
    "\25\0\1\11\1\0\1\11\1\66\1\0\1\11\13\0"+
    "\4\11\1\377\12\11\1\0\10\11\2\0\12\11\25\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\13\0\6\11"+
    "\1\u0100\10\11\1\0\10\11\2\0\12\11\25\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\13\0\6\11\1\u0101"+
    "\10\11\1\0\10\11\2\0\12\11\25\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\13\0\3\11\1\u0102\13\11"+
    "\1\0\10\11\2\0\12\11\54\0\1\u0103\114\0\1\u0104"+
    "\57\0\1\11\1\0\1\11\1\66\1\0\1\11\13\0"+
    "\11\11\1\u0105\5\11\1\0\10\11\2\0\12\11\25\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\13\0\11\11"+
    "\1\u0106\5\11\1\0\10\11\2\0\12\11\25\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\13\0\10\11\1\u0107"+
    "\6\11\1\0\10\11\2\0\12\11\25\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\13\0\17\11\1\0\5\11"+
    "\1\u0108\2\11\2\0\12\11\25\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\13\0\17\11\1\0\10\11\2\0"+
    "\7\11\1\u0109\2\11\25\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\u010a\13\0\17\11\1\0\10\11\2\0\12\11"+
    "\25\0\1\11\1\0\1\11\1\66\1\0\1\11\13\0"+
    "\2\11\1\u010b\14\11\1\0\10\11\2\0\12\11\25\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\u010c\13\0\17\11"+
    "\1\0\10\11\2\0\12\11\21\0\15\254\1\326\2\254"+
    "\1\170\71\254\14\256\1\366\7\256\1\5\65\256\14\u010d"+
    "\1\u010e\75\u010d\14\256\1\255\7\256\1\u010f\65\256\14\0"+
    "\1\u0110\7\0\1\u0111\71\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\13\0\6\11\1\u0112\10\11\1\0\10\11"+
    "\2\0\12\11\25\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\13\0\6\11\1\u0113\10\11\1\0\10\11\2\0"+
    "\12\11\25\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\13\0\10\11\1\u0114\6\11\1\0\10\11\2\0\12\11"+
    "\25\0\1\11\1\0\1\11\1\66\1\0\1\u0115\13\0"+
    "\17\11\1\0\10\11\2\0\12\11\25\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\13\0\5\11\1\u0116\11\11"+
    "\1\0\10\11\2\0\12\11\53\0\1\u0117\104\0\1\u0118"+
    "\70\0\1\11\1\0\1\11\1\66\1\0\1\11\13\0"+
    "\17\11\1\0\2\11\1\u0119\5\11\2\0\12\11\25\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\13\0\17\11"+
    "\1\0\10\11\2\0\1\11\1\u011a\10\11\25\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\13\0\10\11\1\u011b"+
    "\6\11\1\0\10\11\2\0\12\11\25\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\u011c\13\0\17\11\1\0\10\11"+
    "\2\0\12\11\25\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\13\0\17\11\1\0\5\11\1\u011d\2\11\2\0"+
    "\12\11\25\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\13\0\17\11\1\0\10\11\2\0\4\11\1\u011e\5\11"+
    "\21\0\14\u010d\1\u011f\75\u010d\14\0\1\u0120\75\0\14\172"+
    "\1\u0110\7\172\1\0\65\172\4\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\u0121\13\0\17\11\1\0\10\11\2\0"+
    "\12\11\25\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\13\0\6\11\1\u0122\10\11\1\0\10\11\2\0\12\11"+
    "\25\0\1\11\1\0\1\11\1\66\1\0\1\11\13\0"+
    "\13\11\1\u0123\3\11\1\0\10\11\2\0\12\11\56\0"+
    "\1\u0124\107\0\1\u0125\62\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\13\0\2\11\1\u0126\14\11\1\0\10\11"+
    "\2\0\12\11\25\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\13\0\6\11\1\u0127\10\11\1\0\10\11\2\0"+
    "\12\11\25\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\13\0\10\11\1\u0128\6\11\1\0\10\11\2\0\12\11"+
    "\25\0\1\11\1\0\1\11\1\66\1\0\1\11\13\0"+
    "\2\11\1\u0129\14\11\1\0\10\11\2\0\12\11\25\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\13\0\17\11"+
    "\1\0\10\11\2\0\5\11\1\u012a\4\11\21\0\14\u010d"+
    "\1\u011f\7\u010d\1\5\65\u010d\14\0\1\u012b\101\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\13\0\17\11\1\0"+
    "\5\11\1\u012c\2\11\2\0\12\11\25\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\13\0\3\11\1\u012d\13\11"+
    "\1\0\10\11\2\0\12\11\54\0\1\u012e\62\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\13\0\11\11\1\u012f"+
    "\5\11\1\0\10\11\2\0\12\11\25\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\13\0\11\11\1\u0130\5\11"+
    "\1\0\10\11\2\0\12\11\25\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\13\0\17\11\1\0\10\11\2\0"+
    "\6\11\1\u0131\3\11\21\0\14\256\1\0\7\256\1\u0132"+
    "\65\256\4\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\13\0\2\11\1\u0133\14\11\1\0\10\11\2\0\12\11"+
    "\25\0\1\11\1\0\1\11\1\66\1\0\1\11\13\0"+
    "\1\u0134\16\11\1\0\10\11\2\0\12\11\25\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\13\0\13\11\1\u0135"+
    "\3\11\1\0\10\11\2\0\12\11\25\0\1\11\1\0"+
    "\1\11\1\66\1\0\1\11\13\0\5\11\1\u0136\11\11"+
    "\1\0\10\11\2\0\12\11\25\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\13\0\11\11\1\u0137\5\11\1\0"+
    "\10\11\2\0\12\11\25\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\13\0\13\11\1\u0138\3\11\1\0\10\11"+
    "\2\0\12\11\25\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\13\0\14\11\1\u0139\2\11\1\0\10\11\2\0"+
    "\12\11\25\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\13\0\10\11\1\u013a\6\11\1\0\10\11\2\0\12\11"+
    "\25\0\1\11\1\0\1\11\1\66\1\0\1\11\13\0"+
    "\5\11\1\u013b\11\11\1\0\10\11\2\0\12\11\25\0"+
    "\1\11\1\0\1\11\1\66\1\0\1\11\13\0\17\11"+
    "\1\0\10\11\2\0\2\11\1\u013c\7\11\25\0\1\11"+
    "\1\0\1\11\1\66\1\0\1\11\13\0\16\11\1\u013d"+
    "\1\0\10\11\2\0\12\11\25\0\1\11\1\0\1\11"+
    "\1\66\1\0\1\11\13\0\11\11\1\u013e\5\11\1\0"+
    "\10\11\2\0\12\11\25\0\1\11\1\0\1\11\1\66"+
    "\1\0\1\11\13\0\10\11\1\u013f\6\11\1\0\10\11"+
    "\2\0\12\11\25\0\1\11\1\0\1\11\1\66\1\0"+
    "\1\11\13\0\10\11\1\u0140\6\11\1\0\10\11\2\0"+
    "\12\11\25\0\1\11\1\0\1\11\1\66\1\0\1\11"+
    "\13\0\11\11\1\u0141\5\11\1\0\10\11\2\0\12\11"+
    "\25\0\1\11\1\0\1\11\1\66\1\0\1\11\13\0"+
    "\10\11\1\u0142\6\11\1\0\10\11\2\0\12\11\21\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[17612];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\3\11\1\1\1\11\3\1\1\11\1\1\1\11"+
    "\1\1\1\11\24\1\2\11\3\1\13\11\2\0\11\1"+
    "\2\0\1\11\1\0\23\1\2\0\2\1\2\11\5\1"+
    "\5\11\21\1\1\11\4\0\24\1\2\0\31\1\3\0"+
    "\1\1\1\0\15\1\2\0\26\1\3\0\13\1\2\0"+
    "\17\1\2\0\1\1\2\0\11\1\2\0\10\1\2\0"+
    "\1\1\2\0\5\1\2\0\6\1\2\0\3\1\1\0"+
    "\1\11\5\1\1\0\2\1\1\11\3\1\1\0\20\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[322];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    public ArrayList<ErrorC> listaErrores = new ArrayList(); // Lista para almacenar errores.
    public ArrayList<lexema> listaLexemas = new ArrayList(); // Lista para almacenar el flujo de palabras (tokens).
    public String cadena ="";
    public int linea=0,columna = 0;
    public void adderror(int linea, int columna, String valor)
    {        
        listaErrores.add(new ErrorC(ErrorC.TipoError.LEXICO,valor, linea, columna));
    }

    public void addLexema(String tipo, String valor, int linea, int columna)
    {        
        listaLexemas.add(new lexema(tipo, valor, linea, columna));	            
    } 
    public void Imprimir(String cadena)
    {
        System.out.println(cadena);
    }   
 



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scanner(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { 	return new Symbol(sym.EOF);    
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Caracter ilegal: " + yytext()+" Linea : "+yyline +" Columna: "+yychar); 
            adderror(yyline, yychar, yytext());
            }
          case 91: break;
          case 2: 
            { 
            }
          case 92: break;
          case 3: 
            { yychar=0;
            }
          case 93: break;
          case 4: 
            { addLexema("Identificador", yytext(), yyline, yychar);  	  
            if(Long.parseLong(yytext())> Utilidades.Singlenton.maxInt && Long.parseLong(yytext()) < Utilidades.Singlenton.minInt )
            {
                Utilidades.Singlenton.registrarError("Entero", "Número entero demasiado grande", ErrorC.TipoError.SEMANTICO,yyline, yychar);
                return new Symbol(sym.entero, yychar, yyline,0);             
            }   
            return new Symbol(sym.entero, yychar, yyline,Integer.parseInt(yytext()));
            }
          case 94: break;
          case 5: 
            { return new Symbol(sym.punto, yychar, yyline, yytext());
            }
          case 95: break;
          case 6: 
            { addLexema("Identificador", yytext(), yyline, yychar);  	        
            return new Symbol(sym.id, yychar, yyline, yytext().toLowerCase());
            }
          case 96: break;
          case 7: 
            { cadena = "";                    
            yybegin(cad1);
            linea = yyline;
            columna = yychar;
            }
          case 97: break;
          case 8: 
            { return new Symbol(sym.multi, yychar, yyline, yytext());
            }
          case 98: break;
          case 9: 
            { return new Symbol(sym.dospuntos, yychar, yyline, yytext());
            }
          case 99: break;
          case 10: 
            { return new Symbol(sym.menos, yychar, yyline, yytext());
            }
          case 100: break;
          case 11: 
            { return new Symbol(sym.div, yychar, yyline, yytext());
            }
          case 101: break;
          case 12: 
            { return new Symbol(sym.suma, yychar, yyline, yytext());
            }
          case 102: break;
          case 13: 
            { return new Symbol(sym.puntocoma, yychar, yyline, yytext());
            }
          case 103: break;
          case 14: 
            { return new Symbol(sym.coma, yychar, yyline, yytext());
            }
          case 104: break;
          case 15: 
            { return new Symbol(sym.menor, yychar, yyline, yytext());
            }
          case 105: break;
          case 16: 
            { return new Symbol(sym.mayor, yychar, yyline, yytext());
            }
          case 106: break;
          case 17: 
            { return new Symbol(sym.igual, yychar, yyline, yytext());
            }
          case 107: break;
          case 18: 
            { return new Symbol(sym.potencia, yychar, yyline, yytext());
            }
          case 108: break;
          case 19: 
            { return new Symbol(sym.modulo, yychar, yyline, yytext());
            }
          case 109: break;
          case 20: 
            { return new Symbol(sym.pari, yychar, yyline, yytext());
            }
          case 110: break;
          case 21: 
            { return new Symbol(sym.pard, yychar, yyline, yytext());
            }
          case 111: break;
          case 22: 
            { return new Symbol(sym.llavei, yychar, yyline, yytext());
            }
          case 112: break;
          case 23: 
            { return new Symbol(sym.llaved, yychar, yyline, yytext());
            }
          case 113: break;
          case 24: 
            { return new Symbol(sym.corchetei, yychar, yyline, yytext());
            }
          case 114: break;
          case 25: 
            { return new Symbol(sym.corcheted, yychar, yyline, yytext());
            }
          case 115: break;
          case 26: 
            { return new Symbol(sym.not, yychar, yyline, yytext());
            }
          case 116: break;
          case 27: 
            { switch(yytext())
        {
            case "\\":          
                yybegin(cad2);
            break;
            case "\"":      
                yybegin(YYINITIAL);
                return new Symbol(sym.cadena, columna, linea ,cadena);             
            default:
                cadena += yytext();
            break;                
        }
            }
          case 117: break;
          case 28: 
            { switch(yytext())
        {
            case "\'":
                cadena += "\'";
            break;            
            case "\"":
                cadena += "\"";
            break;  
            case "?":
                cadena += "?";
            case "%":
                cadena += "%";
            break;
            case "\\":
                cadena += "\\";
            break;  
            case "0":                
            break;  
            case "a":                
            break;   
            case "b":                
                cadena = cadena.substring(0, cadena.length()-1);
            break; 
            case "v":   
                String partes[] = cadena.split("\n");
                String subcadena = "";
                for(int i = 0 ; i < partes.length-1; i++)
                {
                    subcadena += partes[i];
                }         
                String tabulaciones[] = partes[partes.length].split("\t");
                for(int i = 0; i< tabulaciones.length; i++)
                {
                    subcadena += "\t";
                }
                cadena = subcadena;                                                       
            break;             
            case "n":                
                cadena = cadena + "\n";
            break; 
            case "t":                
                cadena = cadena + "\t";
            break;             
            case "r":       
                partes = cadena.split("\n");
                subcadena = "";
                for(int i = 0 ; i < partes.length-1; i++)
                {
                    subcadena += partes[i];
                }                                       
                cadena = subcadena;
            break;                                                                                                       
            default:
                cadena += "\\"+yytext();
                //Utilidades.Singlenton.registrarError("\\"+yytext(), "Carácter ilegal. Ha sido eliminado.", ErrorC.TipoError.SEMANTICO,yyline, yychar);
            break;                
        }
        yybegin(cad1);
            }
          case 118: break;
          case 29: 
            { return new Symbol(sym.decremento, yychar, yyline, yytext());
            }
          case 119: break;
          case 30: 
            { return new Symbol(sym.si, yychar, yyline, yytext());
            }
          case 120: break;
          case 31: 
            { return new Symbol(sym.and, yychar, yyline, yytext());
            }
          case 121: break;
          case 32: 
            { return new Symbol(sym.or, yychar, yyline, yytext());
            }
          case 122: break;
          case 33: 
            { return new Symbol(sym.aumento, yychar, yyline, yytext());
            }
          case 123: break;
          case 34: 
            { return new Symbol(sym.desigual, yychar, yyline, yytext());
            }
          case 124: break;
          case 35: 
            { return new Symbol(sym.menorigual, yychar, yyline, yytext());
            }
          case 125: break;
          case 36: 
            { return new Symbol(sym.mayorigual, yychar, yyline, yytext());
            }
          case 126: break;
          case 37: 
            { return new Symbol(sym.igualigual, yychar, yyline, yytext());
            }
          case 127: break;
          case 38: 
            { addLexema("Identificador", yytext(), yyline, yychar);  	        
            return new Symbol(sym.decimal, yychar, yyline,Double.parseDouble(yytext()));
            }
          case 128: break;
          case 39: 
            { return new Symbol(sym.escribir, yychar, yyline, yytext());
            }
          case 129: break;
          case 40: 
            { addLexema("Identificador", yytext(), yyline, yychar);  	        
            return new Symbol(sym.caracter, yychar, yyline,yytext().substring(1, yytext().length()-1).charAt(0));
            }
          case 130: break;
          case 41: 
            { return new Symbol(sym.para, yychar, yyline, yytext());
            }
          case 131: break;
          case 42: 
            { return new Symbol(sym.tint, yychar, yyline, yytext());
            }
          case 132: break;
          case 43: 
            { return new Symbol(sym.nulo, yychar, yyline, yytext());
            }
          case 133: break;
          case 44: 
            { return new Symbol(sym.tdouble, yychar, yyline, yytext());
            }
          case 134: break;
          case 45: 
            { return new Symbol(sym.tchar, yychar, yyline, yytext());
            }
          case 135: break;
          case 46: 
            { return new Symbol(sym.tbool, yychar, yyline, yytext());
            }
          case 136: break;
          case 47: 
            { return new Symbol(sym.tvoid, yychar, yyline, yytext());
            }
          case 137: break;
          case 48: 
            { return new Symbol(sym.print, yychar, yyline, yytext());
            }
          case 138: break;
          case 49: 
            { return new Symbol(sym.msn, yychar, yyline, yytext());
            }
          case 139: break;
          case 50: 
            { return new Symbol(sym.sino, yychar, yyline, yytext());
            }
          case 140: break;
          case 51: 
            { return new Symbol(sym.continuar, yychar, yyline, yytext());
            }
          case 141: break;
          case 52: 
            { return new Symbol(sym.booleano,yychar, yyline, true);
            }
          case 142: break;
          case 53: 
            { return new Symbol(sym.caso, yychar, yyline, yytext());
            }
          case 143: break;
          case 54: 
            { return new Symbol(sym.donde, yychar, yyline, yytext());
            }
          case 144: break;
          case 55: 
            { return new Symbol(sym.tetiqueta, yychar, yyline, yytext());
            }
          case 145: break;
          case 56: 
            { return new Symbol(sym.ttexto, yychar, yyline, yytext());
            }
          case 146: break;
          case 57: 
            { return new Symbol(sym.teql, yychar, yyline, yytext());
            }
          case 147: break;
          case 58: 
            { return new Symbol(sym.tread, yychar, yyline, yytext());
            }
          case 148: break;
          case 59: 
            { return new Symbol(sym.taentero, yychar, yyline, yytext());
            }
          case 149: break;
          case 60: 
            { return new Symbol(sym.tatexto, yychar, yyline, yytext());
            }
          case 150: break;
          case 61: 
            { return new Symbol(sym.tadecimal, yychar, yyline, yytext());
            }
          case 151: break;
          case 62: 
            { return new Symbol(sym.tconcatenar, yychar, yyline, yytext());
            }
          case 152: break;
          case 63: 
            { return new Symbol(sym.tcopi, yychar, yyline, yytext());
            }
          case 153: break;
          case 64: 
            { return new Symbol(sym.booleano,yychar, yyline, false);
            }
          case 154: break;
          case 65: 
            { return new Symbol(sym.mientras, yychar, yyline, yytext());
            }
          case 155: break;
          case 66: 
            { return new Symbol(sym.ttextoNum, yychar, yyline, yytext());
            }
          case 156: break;
          case 67: 
            { return new Symbol(sym.ttextoPass, yychar, yyline, yytext());
            }
          case 157: break;
          case 68: 
            { return new Symbol(sym.ttextoArea, yychar, yyline, yytext());
            }
          case 158: break;
          case 69: 
            { return new Symbol(sym.tapend, yychar, yyline, yytext());
            }
          case 159: break;
          case 70: 
            { return new Symbol(sym.tclose, yychar, yyline, yytext());
            }
          case 160: break;
          case 71: 
            { return new Symbol(sym.escritura, yychar, yyline, yytext());
            }
          case 161: break;
          case 72: 
            { return new Symbol(sym.tfusion, yychar, yyline, yytext());
            }
          case 162: break;
          case 73: 
            { return new Symbol(sym.switch_, yychar, yyline, yytext());
            }
          case 163: break;
          case 74: 
            { return new Symbol(sym.hacer, yychar, yyline, yytext());
            }
          case 164: break;
          case 75: 
            { return new Symbol(sym.romper, yychar, yyline, yytext());
            }
          case 165: break;
          case 76: 
            { return new Symbol(sym.tboton, yychar, yyline, yytext());
            }
          case 166: break;
          case 77: 
            { return new Symbol(sym.tpeso, yychar, yyline, yytext());
            }
          case 167: break;
          case 78: 
            { return new Symbol(sym.repetir, yychar, yyline, yytext());
            }
          case 168: break;
          case 79: 
            { return new Symbol(sym.defecto, yychar, yyline, yytext());
            }
          case 169: break;
          case 80: 
            { return new Symbol(sym.tstring, yychar, yyline, yytext());
            }
          case 170: break;
          case 81: 
            { return new Symbol(sym.retorno, yychar, yyline, yytext());
            }
          case 171: break;
          case 82: 
            { return new Symbol(sym.tdefinir, yychar, yyline, yytext());
            }
          case 172: break;
          case 83: 
            { return new Symbol(sym.tmensaje, yychar, yyline, yytext());
            }
          case 173: break;
          case 84: 
            { return new Symbol(sym.treservar, yychar, yyline, yytext());
            }
          case 174: break;
          case 85: 
            { return new Symbol(sym.importar, yychar, yyline, yytext());
            }
          case 175: break;
          case 86: 
            { return new Symbol(sym.tnuevogui,yychar,yyline,yytext());
            }
          case 176: break;
          case 87: 
            { return new Symbol(sym.tclick, yychar, yyline, yytext());
            }
          case 177: break;
          case 88: 
            { return new Symbol(sym.tanchoalto,yychar,yyline,yytext());
            }
          case 178: break;
          case 89: 
            { return new Symbol(sym.tabrirventana,yychar,yyline,yytext());
            }
          case 179: break;
          case 90: 
            { return new Symbol(sym.tiniciarventana, yychar, yyline, yytext());
            }
          case 180: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
