
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int twrite = 62;
  public static final int tatexto = 56;
  public static final int menos = 95;
  public static final int tconcatenar = 55;
  public static final int menor = 22;
  public static final int punto = 84;
  public static final int nulo = 27;
  public static final int booleano = 105;
  public static final int decremento = 83;
  public static final int leerarchivo = 66;
  public static final int print = 16;
  public static final int tchar = 4;
  public static final int suma = 94;
  public static final int importar = 44;
  public static final int tochar = 71;
  public static final int println = 17;
  public static final int tvoid = 26;
  public static final int twriteend = 63;
  public static final int aumento = 82;
  public static final int div = 97;
  public static final int tapend = 52;
  public static final int romper = 78;
  public static final int cadena = 101;
  public static final int dospuntos = 81;
  public static final int mientras = 76;
  public static final int menorigual = 23;
  public static final int abstracto = 30;
  public static final int tfusion = 54;
  public static final int privado = 47;
  public static final int sino = 90;
  public static final int tint = 2;
  public static final int toint = 73;
  public static final int decimal = 104;
  public static final int caso = 31;
  public static final int try_ = 75;
  public static final int sinosi = 89;
  public static final int msn = 39;
  public static final int treservar = 60;
  public static final int str_ = 74;
  public static final int llavei = 8;
  public static final int or = 87;
  public static final int tcomodin = 28;
  public static final int caracter = 102;
  public static final int llaved = 9;
  public static final int extiende = 36;
  public static final int mayorigual = 24;
  public static final int nuevo = 46;
  public static final int tolower = 92;
  public static final int id = 12;
  public static final int retorno = 50;
  public static final int cerrar = 43;
  public static final int estatico = 67;
  public static final int desigual = 20;
  public static final int tcopi = 51;
  public static final int tdefinir = 53;
  public static final int cat = 32;
  public static final int protegido = 48;
  public static final int puntocoma = 7;
  public static final int and = 86;
  public static final int mayor = 21;
  public static final int tclose = 64;
  public static final int printable = 99;
  public static final int xor = 98;
  public static final int tbool = 5;
  public static final int EOF = 0;
  public static final int taentero = 57;
  public static final int tpeso = 59;
  public static final int escribir = 41;
  public static final int super_ = 68;
  public static final int tstring = 6;
  public static final int repetir = 65;
  public static final int este = 70;
  public static final int tread = 29;
  public static final int tostring = 91;
  public static final int publico = 49;
  public static final int escritura = 42;
  public static final int potencia = 25;
  public static final int corchetei = 13;
  public static final int touper = 93;
  public static final int multi = 96;
  public static final int interrogante = 80;
  public static final int error = 1;
  public static final int switch_ = 69;
  public static final int corcheted = 14;
  public static final int continuar = 79;
  public static final int si = 88;
  public static final int entero = 103;
  public static final int graph = 38;
  public static final int pari = 10;
  public static final int hacer = 35;
  public static final int defecto = 34;
  public static final int igualigual = 19;
  public static final int donde = 40;
  public static final int pard = 11;
  public static final int para = 77;
  public static final int tdouble = 3;
  public static final int coma = 18;
  public static final int instanceof_ = 45;
  public static final int modulo = 100;
  public static final int not = 85;
  public static final int final_ = 37;
  public static final int igual = 15;
  public static final int todouble = 72;
  public static final int clase = 33;
  public static final int tadecimal = 58;
  public static final int teql = 61;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "tint",
  "tdouble",
  "tchar",
  "tbool",
  "tstring",
  "puntocoma",
  "llavei",
  "llaved",
  "pari",
  "pard",
  "id",
  "corchetei",
  "corcheted",
  "igual",
  "print",
  "println",
  "coma",
  "igualigual",
  "desigual",
  "mayor",
  "menor",
  "menorigual",
  "mayorigual",
  "potencia",
  "tvoid",
  "nulo",
  "tcomodin",
  "tread",
  "abstracto",
  "caso",
  "cat",
  "clase",
  "defecto",
  "hacer",
  "extiende",
  "final_",
  "graph",
  "msn",
  "donde",
  "escribir",
  "escritura",
  "cerrar",
  "importar",
  "instanceof_",
  "nuevo",
  "privado",
  "protegido",
  "publico",
  "retorno",
  "tcopi",
  "tapend",
  "tdefinir",
  "tfusion",
  "tconcatenar",
  "tatexto",
  "taentero",
  "tadecimal",
  "tpeso",
  "treservar",
  "teql",
  "twrite",
  "twriteend",
  "tclose",
  "repetir",
  "leerarchivo",
  "estatico",
  "super_",
  "switch_",
  "este",
  "tochar",
  "todouble",
  "toint",
  "str_",
  "try_",
  "mientras",
  "para",
  "romper",
  "continuar",
  "interrogante",
  "dospuntos",
  "aumento",
  "decremento",
  "punto",
  "not",
  "and",
  "or",
  "si",
  "sinosi",
  "sino",
  "tostring",
  "tolower",
  "touper",
  "suma",
  "menos",
  "multi",
  "div",
  "xor",
  "printable",
  "modulo",
  "cadena",
  "caracter",
  "entero",
  "decimal",
  "booleano"
  };
}

